import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Infratech.pl',
  description: 'Generated by Next.js',
};

const inter = Inter({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pl'>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
